CAMERA_BACKEND_CHOICES = ("auto", "opencv", "picamera2", "libcamera")
DEFAULT_CAMERA_BACKEND = "auto"
DEFAULT_CAMERA_DEVICE_INDEX = 0
DEFAULT_CAMERA_WIDTH = 640
DEFAULT_CAMERA_HEIGHT = 640 #480
DEFAULT_CAMERA_STREAM_FPS = 5.0
DEFAULT_CAMERA_OUTPUT = "captures/camera_test.jpg"
DEFAULT_CAMERA_STREAM_OUTPUT = "captures/camera_stream_last.jpg"


LIDAR_PROTOCOL_CHOICES = ("hokuyo", "raw")
DEFAULT_LIDAR_PROTOCOL = "hokuyo"
DEFAULT_LIDAR_PORT = "/dev/ttyACM0"
DEFAULT_LIDAR_BAUDRATE = 115200
DEFAULT_LIDAR_TIMEOUT = 1.0
DEFAULT_LIDAR_MAX_EMPTY_READS = 10


DEFAULT_HOKUYO_START_STEP = 256
DEFAULT_HOKUYO_END_STEP = 512
DEFAULT_HOKUYO_CLUSTER_COUNT = 0


DEFAULT_LIDAR_START_ANGLE_DEG = -22.5
DEFAULT_LIDAR_END_ANGLE_DEG = 22.5
DEFAULT_LIDAR_MIN_DISTANCE_MM = 20.0
DEFAULT_LIDAR_MAX_DISTANCE_MM = 2000.0


DEFAULT_STREAM_DURATION = 10.0
DEFAULT_MAX_FUSION_SAMPLES = 20
